import pathlib
from fractions import Fraction
from random import choice, seed

import abjad
import baca
import evans
from abjadext import rmakers

import cairn


def beam_position(selection, position):
    first_leaf = abjad.select.leaf(selection, 0)
    abjad.override(first_leaf).Beam.positions = rf"#'({position} . {position})"


pitch_sequence = [
    -17,
    -15,
    -13,
    -15,
    -12,
    -10,
    -15,
    -13,
    -10,
    -8,
    -7,
    -15,
    -13,
    -8,
    -10,
    -8,
    -7,
    -5,
    -3,
    -5,
    -7,
    -8,
    -12,
    -10,
    -12,
    -13,
    -10,
    -8,
    -7,
    -5,
    -3,
    0,
    -1,
    -3,
    -5,
    -1,
    2,
    -3,
    2,
    -5,
    -3,
    0,
    -5,  # after here breaks
    2,
    4,
    5,
    7,
    9,
    11,
    12,
    14,
    16,
    17,
    16,
    17,
    16,
    14,
    11,
    14,
    12,
    11,
    9,
    7,
    5,
    4,
    2,
    0,
    # signs changed here
    -12 + 13,
    -13 + 13,
    -15 + 13,
    -17 + 13,
    -13 + 13,
    -12 + 13,
    -15 + 13,
    -12 + 13,
    -10 + 13,
    -8 + 13,
    -12 + 13,
    -7 + 13,
    -10 + 13,
    #
    -5 + 2,
    -4 + 2,
    -3 + 2,
    -2 + 2,
    -1 + 2,
    0 + 2,
    1 + 2,
    2 + 2,
    3 + 2,
]

cyc_staves = evans.CyclicList(
    [
        0,
        1,
        1,
        0,
        1,
        0,
        0,
        1,
        2,
        1,
        0,
        0,
        1,
        0,
        1,
        2,
        2,
        0,
        1,
        0,
        1,
        0,
        2,
        2,
        1,
        0,
        0,
        1,
        0,
        1,
        2,
        1,
        2,
        2,
        1,
        2,
        1,
        0,
        2,
        2,
        1,
        2,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        2,
        2,
        2,
        2,
        2,
        1,
        2,
        1,
        2,
        2,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        1,
        0,
        2,
        2,
        2,
        1,
        0,
        1,
        0,
        1,
        2,
        0,
        1,
        1,
        1,
        2,
        1,
        0,
    ],
    forget=False,
)

pizz_seq = []
for i in pitch_sequence:
    staff = cyc_staves(r=1)[0]
    if staff == 1:
        pizz_seq.append(i)
    else:
        pizz_seq.append(0)

maker = evans.SegmentMaker(
    instruments=cairn.instruments,
    names=[
        '"SCP"',
        '"BCP"',
        '"Mano Destra"',
        '"Mano Sinestra"',
        '"Davanti"',
        '" "',
        '" "',
        '"Dietro"',
        '"Archi"',
    ],
    abbreviations=[
        '"SCP"',
        '"BCP"',
        '"mn dst"',
        '"man sin"',
        '"davanti"',
        '" "',
        '" "',
        '"dietro"',
        '"archi"',
    ],
    name_staves=True,
    fermata_measures=cairn.fermata_measures_26,
    commands=[
        ## Cello
        evans.attach(
            "cello voice",
            abjad.Clef("bass"),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "string voice",
            abjad.LilyPondLiteral(r"\stopStaff", site="before"),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "string voice",
            abjad.LilyPondLiteral(
                r"\override Staff.StaffSymbol.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "string voice",
            abjad.LilyPondLiteral(
                r"\override Staff.Dots.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "string voice",
            abjad.LilyPondLiteral(r"\startStaff", site="before"),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "change voice",
            abjad.LilyPondLiteral(r"\stopStaff", site="before"),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "change voice",
            abjad.LilyPondLiteral(
                r"\override Staff.StaffSymbol.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "change voice",
            abjad.LilyPondLiteral(r"\startStaff", site="before"),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "change voice",
            abjad.LilyPondLiteral(
                r"\override Staff.Rest.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "change voice",
            abjad.LilyPondLiteral(
                r"\override Staff.Dots.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "left voice",
            abjad.LilyPondLiteral(r"\stopStaff", site="before"),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "left voice",
            abjad.LilyPondLiteral(
                r"\override Staff.StaffSymbol.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "left voice",
            abjad.LilyPondLiteral(r"\startStaff", site="before"),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "left voice",
            abjad.LilyPondLiteral(
                r"\override Staff.Rest.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "left voice",
            abjad.LilyPondLiteral(
                r"\override Staff.Dots.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "right voice",
            abjad.LilyPondLiteral(r"\stopStaff", site="before"),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "right voice",
            abjad.LilyPondLiteral(
                r"\override Staff.StaffSymbol.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "right voice",
            abjad.LilyPondLiteral(r"\startStaff", site="before"),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "right voice",
            abjad.LilyPondLiteral(
                r"\override Staff.Rest.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "right voice",
            abjad.LilyPondLiteral(
                r"\override Staff.Dots.transparent = ##t", site="before"
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        #### MUSIC
        evans.MusicCommand(
            ("front voice", (0, 4)),
            evans.multiplied_duration(
                (1, 16),
                preprocessor=evans.make_preprocessor(
                    sum=True,
                    split_divisions_by_proportions=[
                        (
                            6,
                            2,
                            5,
                            3,
                            2,
                            2,
                            2,
                            3,
                            3,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            3,
                            2,
                            4,
                            2,
                            2,
                            2,
                            6,
                            4,
                            2,
                            2,
                            2,
                            2,
                            2,
                            3,
                            1,
                            3,
                            1,
                            1,
                            7,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            2,
                            2,
                            2,
                            2,
                            2,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            4,
                            1,
                            3,
                            1,
                            1,
                            5,
                            2,
                            2,
                            2,
                            4,
                            5,
                            8,
                            1,
                            1,
                            1,
                            1,
                            3,
                            3,
                            3,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            4,
                            13,
                            6,
                            6,
                        )
                    ],
                ),
            ),
            evans.PitchHandler(
                pizz_seq,
            ),
            evans.NoteheadHandler(
                ["cross"],
                head_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    1,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    1,
                    0,
                    0,
                    1,
                    1,
                    0,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    1,
                    1,
                    1,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                ],
            ),
            abjad.beam,
            lambda _: beam_position(_, 5),
            evans.staff_changes(
                reservoir=["front staff", "cello staff", "back staff"],
                sequence=[
                    0,
                    1,
                    1,
                    0,
                    1,
                    0,
                    0,
                    1,
                    2,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                    2,
                    2,
                    0,
                    1,
                    0,
                    1,
                    0,
                    2,
                    2,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                    2,
                    1,
                    2,
                    2,
                    1,
                    2,
                    1,
                    0,
                    2,
                    2,
                    1,
                    2,
                    1,
                    0,
                    1,
                    0,
                    1,
                    0,
                    1,
                    0,
                    1,
                    0,
                    1,
                    0,
                    2,
                    2,
                    2,
                    2,
                    2,
                    1,
                    2,
                    1,
                    2,
                    2,
                    0,
                    1,
                    0,
                    1,
                    0,
                    1,
                    0,
                    1,
                    0,
                    2,
                    2,
                    2,
                    1,
                    0,
                    1,
                    0,
                    1,
                    2,
                    0,
                    1,
                    1,
                    1,
                    2,
                    1,
                    0,
                ],
            ),
            abjad.LilyPondLiteral(r"\my-hack-slash", site="before"),
            abjad.Markup(r"\markup pizz."),
            evans.Attachment(
                abjad.Markup(r'\markup \italic "spatial notation"'),
                selector=lambda _: abjad.select.leaf(_, 0),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("p"),
                selector=lambda _: abjad.select.leaf(_, 0),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("mp"),
                selector=lambda _: abjad.select.leaf(_, 1 + 2),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Articulation("+"),
                selector=lambda _: abjad.select.leaf(_, 1),
                direction=abjad.DOWN,
            ),
            evans.Attachment(
                abjad.Markup(r"\markup (simile)"),
                selector=lambda _: abjad.select.leaf(_, 2),
            ),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 3 + 2 + 2 - 1),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("p"),
                selector=lambda _: abjad.select.leaf(_, 4 + 2 + 2 + 2),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("mf"),
                selector=lambda _: abjad.select.leaf(_, 8 + 2 + 2 + 2 + 2),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, 10 + 2 + 2 + 2 + 2 + 2 - 1),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("mp"),
                selector=lambda _: abjad.select.leaf(_, 13 + 2 + 2 + 2 + 2 + 2 + 2),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 37),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.StartHairpin("--"),
                selector=lambda _: abjad.select.leaf(_, 37),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.StartHairpin("<"),
                selector=lambda _: abjad.select.leaf(_, 43),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("fff"),
                selector=lambda _: abjad.select.leaf(_, 53),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("p"),
                selector=lambda _: abjad.select.leaf(_, 64),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.StartHairpin("<"),
                selector=lambda _: abjad.select.leaf(_, 64),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("mf"),
                selector=lambda _: abjad.select.leaf(_, 70),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 70),
                direction=abjad.UP,
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, 82),
                direction=abjad.UP,
            ),
        ),
        evans.MusicCommand(
            ("cello voice", (0, 4)),
            evans.multiplied_duration(
                (1, 1),
                preprocessor=evans.make_preprocessor(
                    sum=True,
                    split_divisions_by_proportions=[
                        (
                            6,
                            2,
                            5,
                            3,
                            2,
                            2,
                            2,
                            3,
                            3,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            3,
                            2,
                            4,
                            2,
                            2,
                            2,
                            6,
                            4,
                            2,
                            2,
                            2,
                            2,
                            2,
                            3,
                            1,
                            3,
                            1,
                            1,
                            7,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            2,
                            2,
                            2,
                            2,
                            2,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            4,
                            1,
                            3,
                            1,
                            1,
                            5,
                            2,
                            2,
                            2,
                            4,
                            5,
                            8,
                            1,
                            1,
                            1,
                            1,
                            3,
                            3,
                            3,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            4,
                            13,
                            6,
                            6,
                        )
                    ],
                ),
            ),
            evans.PitchHandler(
                pitch_sequence,
            ),
            evans.gliss_only,
            abjad.Markup(r"\markup (III)"),
            # evans.Attachment(
            #     abjad.Clef("tenor"),
            #     selector=lambda _: abjad.select.leaf(_, 31),
            # ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 31 + 15),
            ),
            # evans.Attachment(
            #     abjad.Clef("bass"),
            #     selector=lambda _: abjad.select.leaf(_, 31+15+22),
            # ),
        ),
        evans.attach(
            "back voice",
            abjad.LilyPondLiteral(
                [
                    r"\override Staff.Rest.stencil = ##f",
                    r"\override Staff.Dots.stencil = ##f",
                ],
                site="before",
            ),
            selector=lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "back voice",
            abjad.LilyPondLiteral(
                [
                    r"\override Staff.Rest.stencil = ##t",
                    r"\override Staff.Dots.stencil = ##t",
                ],
                site="after",
            ),
            selector=lambda _: abjad.select.leaf(_, -1),
        ),
        #### Cleanup
        # evans.call(
        #     "score",
        #     evans.SegmentMaker.beam_score_without_splitting,
        #     lambda _: abjad.select.components(_, abjad.Score),
        # ),
        # evans.attach(
        #     "Global Context",
        #     cairn.lib.mark_78,
        #     lambda _: abjad.select.leaf(_, 0),
        # ),
        evans.attach(
            "Global Context",
            cairn.lib.met_78,
            lambda _: abjad.select.leaf(_, 0),
        ),
        ####
        # TIME BRACKETS
        ####
        evans.call(
            "Global Context",
            evans.bracket_time_duration,
            selector=evans.select_measures([0, 1, 2, 3], leaves=[0, 1, 2, 3]),
        ),
        ####
        evans.attach(
            "Global Context",
            abjad.bundle(
                abjad.Markup(
                    r'\boxed-markup-upright "6.A: que se piedra en la noche sin canto de los peces" 2'
                ),
                r"\tweak padding 5",
            ),
            lambda _: abjad.select.leaf(_, 0),
            direction=abjad.UP,
        ),
    ],
    score_template=cairn.score,
    transpose_from_sounding_pitch=False,
    time_signatures=cairn.signatures_26,
    clef_handlers=None,
    tuplet_bracket_noteheads=False,
    add_final_grand_pause=False,
    score_includes=[
        "abjad.ily",
        "../../build/segment_stylesheet.ily",
    ],
    segment_name="26",
    current_directory=pathlib.Path(__file__).parent,
    cutaway=False,
    beam_pattern="meter",
    beam_rests=True,
    barline="|.",
    rehearsal_mark="",
    fermata="scripts.ufermata",
    with_layout=True,
    mm_rests=False,
    extra_rewrite=False,  # should default to false but defaults to true
    print_clock_time=True,
    color_out_of_range=False,
    name_columns=True,
)

maker.build_segment()
